// <auto-generated />
using System;
using AppConsulta.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppConsulta.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180929022734_TabelaConsulta")]
    partial class TabelaConsulta
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AppConsulta.Models.Consulta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("hrFinal");

                    b.Property<DateTime>("hraConsulta");

                    b.Property<int?>("pacienteid");

                    b.Property<string>("tipo");

                    b.Property<int>("valor");

                    b.HasKey("id");

                    b.HasIndex("pacienteid");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("AppConsulta.Models.Paciente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("convenio");

                    b.Property<string>("email");

                    b.Property<string>("endereco");

                    b.Property<int>("nascimento");

                    b.Property<string>("nome");

                    b.Property<string>("telefone");

                    b.Property<string>("tipo");

                    b.HasKey("id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("AppConsulta.Models.Consulta", b =>
                {
                    b.HasOne("AppConsulta.Models.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("pacienteid");
                });
#pragma warning restore 612, 618
        }
    }
}
