// <auto-generated />
using System;
using AppPeople.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppPeople.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180914230422_CidadesHasManyPeople")]
    partial class CidadesHasManyPeople
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AppPeople.Models.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("AppPeople.Models.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("cityid");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("cityid");

                    b.ToTable("People");
                });

            modelBuilder.Entity("AppPeople.Models.Person", b =>
                {
                    b.HasOne("AppPeople.Models.City", "city")
                        .WithMany()
                        .HasForeignKey("cityid");
                });
#pragma warning restore 612, 618
        }
    }
}
