// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using ToDoList.Repositories;

namespace ToDoList.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181109175515_users crud")]
    partial class userscrud
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("ToDoList.Domain.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.Property<int?>("todoid");

                    b.HasKey("id");

                    b.HasIndex("todoid");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ToDoList.Domain.ToDo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descricao");

                    b.HasKey("id");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("ToDoList.Domain.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToDoList.Domain.Item", b =>
                {
                    b.HasOne("ToDoList.Domain.ToDo", "todo")
                        .WithMany("items")
                        .HasForeignKey("todoid");
                });
#pragma warning restore 612, 618
        }
    }
}
